# Array Creation

In [1]:
import numpy as np

In [2]:
a= np.array([1,2,3])   # create an array from a list
print("Array a:", a)

Array a: [1 2 3]


In [5]:
b= np.arange(0,10,3)     # values from 0 to 10 with step 3
print("Array b:", b)

Array b: [0 3 6 9]


In [7]:
d= np.zeros((2,3))      # 2x3 array of zeros
print("Array d:\n",d)

Array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
d= np.zeros((2,3), dtype=int)      # 2x3 array of zeros
print("Array d:\n",d)

Array d:
 [[0 0 0]
 [0 0 0]]


In [11]:
e= np.ones((2,3), dtype=int)  # 2x3 array of ones
print("Array e:\n", e)

Array e:
 [[1 1 1]
 [1 1 1]]


In [10]:
e= np.ones((3,2), dtype=int)
print("Array e:\n", e)

Array e:
 [[1 1]
 [1 1]
 [1 1]]


In [12]:
f= np.eye(4)   # 4x4 identity matrix
print("Identity matrix f:\n",f)

Identity matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [13]:
f= np.eye(4 , dtype=int)   # 4x4 identity matrix
print("Identity matrix f:\n",f)

Identity matrix f:
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


# Array Manipulation Functions

In [16]:
a1= np.array([1,2,3])
reshaped= np.reshape(a1,(3,1))    # reshape to 3x1
print("Reshaped Array:\n", reshaped)

Reshaped Array:
 [[1]
 [2]
 [3]]


In [18]:
f1= np.array([[1,2],[3,4],[5,6],[7,8]])
flattened= np.ravel(f1)    # flatten to 1D array
print("Flattened array:", flattened)

Flattened array: [1 2 3 4 5 6 7 8]


In [19]:
f1= np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
flattened= np.ravel(f1)   
print("Flattened array:", flattened)

Flattened array: [ 1  2  3  4  5  6  7  8  9 10]


In [22]:
e1= np.array([[1,2],[3,4]])
e1

array([[1, 2],
       [3, 4]])

In [23]:
e1= np.array([[1,2],[3,4]])
transposed= np.transpose(e1)    # Transpose the array
print("Transposed Array:\n", transposed)

Transposed Array:
 [[1 3]
 [2 4]]


In [25]:
a2= np.array([1,2])
b2= np.array([3,4])
stacked= np.vstack([a2,b2])    # stack a and b vertically
print("Stacked array:\n", stacked)

Stacked array:
 [[1 2]
 [3 4]]


In [26]:
a2= np.array([1,2])
b2= np.array([3,4])
print(a2)
print(b2)

[1 2]
[3 4]


In [27]:
a2= np.array([1,2])
b2= np.array([3,4])
stacked= np.hstack([a2,b2])    # stack a and b horizentally
print("Stacked array:\n", stacked)

Stacked array:
 [1 2 3 4]


# Mathematical Funcation

In [28]:
g= np.array([1,2,3,4])
added = np.add(g,2)  # adding 2 in each element
print("Adding 2 to g:", added)

Adding 2 to g: [3 4 5 6]


In [29]:
g= np.array([0,1,2,3,4])
added = np.add(g,2)  
print("Adding 2 to g:", added)

Adding 2 to g: [2 3 4 5 6]


In [35]:
squared= np.power(g,2)    # squared of the each element
print("Squared of g:", squared)

Squared of g: [ 0  1  4  9 16]


In [31]:
a3= np.array([1,2,3])
dot_product= np.dot(a3,g)
print("Dot Product of a3 and g:", dot_product)

ValueError: shapes (3,) and (5,) not aligned: 3 (dim 0) != 5 (dim 0)

In [32]:
a

array([1, 2, 3])

In [33]:
a3

array([1, 2, 3])

In [34]:
g

array([0, 1, 2, 3, 4])

In [37]:
a3= np.array([1,2,3])
dot_product= np.dot(a3,a)     # Dot product of a3 and a
print("Dot Product of a3 and a:", dot_product)

Dot Product of a3 and a: 14


# Statistical Function

In [40]:
s= np.array([1,2,3,4])
mean= np.mean(s)   # Mean value of this array
print("Mean value of s:", mean)

Mean value of s: 2.5


In [44]:
var = np.var(s)   # variation of an array
print("variance of s:", var)

variance of s: 1.25


In [46]:
std_dev= np.std(s)        # standard deviation of an array
print("standard deviation of s:", std_dev)

standard deviation of s: 1.118033988749895


In [47]:
minimum= np.min(s)        # minimum element of an array
print("Minimum value of s:", minimum)

Minimum value of s: 1


In [49]:
maximum= np.max(s)        # maximum element of an array
print("maximum value of s:", maximum)

maximum value of s: 4


# Random Sampling Function

In [52]:
random_vals= np.random.rand(3)
print("Random values:", random_vals)

Random values: [0.07983642 0.26164131 0.03004156]


In [56]:
np.random.seed(0)    # seed function can stop the reproducibility
random_vals= np.random.rand(3)  
print("random values:", random_vals)

random values: [0.5488135  0.71518937 0.60276338]


In [57]:
np.random.seed(0)    # seed function can stop the reproducibility
random_vals= np.random.rand(3)  
print("random values:", random_vals)

random values: [0.5488135  0.71518937 0.60276338]


In [64]:
rand_int= np.random.randint(0,10, size=5)   # random integers between 0 to 10
print("random integers:", rand_int)

random integers: [5 0 2 3 8]


In [63]:
rand_int= np.random.randint(0,10, size=5)
print("random integers:", rand_int)

random integers: [9 4 3 0 3]


In [68]:
np.random.seed(0)    # seed function can stop the reproducibility of random numbers
random_int= np.random.randint(0,10, size=5)  
print("random values:", random_int)

random values: [5 0 3 3 7]
