# Numpy Class-2

In [7]:
import numpy as np

In [2]:
np.random.randint(1,5,3)

array([4, 3, 4], dtype=int32)

In [76]:
np.random.randint(1,5,4)        # 4 number print between 1 to 5

array([1, 1, 3, 4], dtype=int32)

In [6]:
np.random.randn(3)

array([ 1.6389505 , -1.42088291,  0.92372459])

In [8]:
np.random.rand(3)

array([0.97395795, 0.06078912, 0.70962222])

In [9]:
np.random.randint(5,2,3)

ValueError: low >= high

In [10]:
np.random.randint(-5,2,3)

array([-3, -5, -1], dtype=int32)

In [12]:
np.random.randint(-5,2,3)

array([ 0, -2, -1], dtype=int32)

In [17]:
np.random.randint(10,40,(10,10))

array([[25, 25, 19, 22, 17, 33, 33, 28, 35, 26],
       [33, 10, 20, 26, 22, 28, 34, 11, 10, 22],
       [14, 22, 26, 31, 33, 21, 10, 18, 35, 14],
       [16, 18, 32, 37, 32, 31, 31, 14, 16, 36],
       [24, 23, 31, 16, 31, 26, 15, 13, 38, 33],
       [13, 33, 11, 28, 33, 15, 18, 23, 25, 17],
       [16, 35, 28, 39, 14, 12, 25, 11, 13, 27],
       [26, 15, 17, 36, 15, 22, 28, 26, 39, 20],
       [23, 39, 38, 11, 22, 24, 35, 24, 26, 26],
       [33, 21, 16, 34, 37, 13, 33, 30, 18, 30]], dtype=int32)

In [14]:
np.random.randint(1,10,(3,3))

array([[7, 5, 8],
       [7, 9, 7],
       [8, 6, 2]], dtype=int32)

In [18]:
ri= np.random.randint(10,40,(10,10))
ri

array([[33, 16, 11, 22, 16, 36, 12, 28, 27, 37],
       [22, 24, 33, 20, 18, 14, 17, 26, 32, 18],
       [34, 23, 14, 35, 18, 24, 19, 39, 12, 17],
       [15, 36, 39, 28, 26, 13, 24, 23, 36, 15],
       [34, 12, 21, 13, 35, 26, 32, 21, 18, 18],
       [14, 12, 16, 24, 23, 35, 15, 16, 24, 17],
       [33, 20, 29, 21, 26, 11, 26, 27, 32, 33],
       [28, 18, 24, 23, 35, 31, 18, 21, 39, 34],
       [35, 13, 32, 10, 20, 36, 16, 28, 35, 11],
       [29, 17, 34, 14, 37, 13, 29, 13, 13, 22]], dtype=int32)

In [19]:
len(ri) # it will print bydefault rows

10

In [20]:
ri1= np.random.randint(1,10,(3,3))
ri1

array([[8, 2, 1],
       [2, 8, 3],
       [4, 5, 1]], dtype=int32)

In [21]:
len(ri1)

3

In [22]:
ri

array([[33, 16, 11, 22, 16, 36, 12, 28, 27, 37],
       [22, 24, 33, 20, 18, 14, 17, 26, 32, 18],
       [34, 23, 14, 35, 18, 24, 19, 39, 12, 17],
       [15, 36, 39, 28, 26, 13, 24, 23, 36, 15],
       [34, 12, 21, 13, 35, 26, 32, 21, 18, 18],
       [14, 12, 16, 24, 23, 35, 15, 16, 24, 17],
       [33, 20, 29, 21, 26, 11, 26, 27, 32, 33],
       [28, 18, 24, 23, 35, 31, 18, 21, 39, 34],
       [35, 13, 32, 10, 20, 36, 16, 28, 35, 11],
       [29, 17, 34, 14, 37, 13, 29, 13, 13, 22]], dtype=int32)

In [25]:
ri.shape      # it will print the size/ shape of that matrix

(10, 10)

# Slicing in Numpy

In [26]:
ri1[:]

array([[8, 2, 1],
       [2, 8, 3],
       [4, 5, 1]], dtype=int32)

In [28]:
ri1[1]

array([2, 8, 3], dtype=int32)

In [29]:
ri= np.random.randint(10,40,(3,5))

In [30]:
ri

array([[15, 22, 31, 11, 11],
       [19, 21, 39, 27, 38],
       [37, 17, 17, 19, 36]], dtype=int32)

In [31]:
ri[0:3]

array([[15, 22, 31, 11, 11],
       [19, 21, 39, 27, 38],
       [37, 17, 17, 19, 36]], dtype=int32)

In [32]:
ri_1= np.random.randint(10,40,(10,10))
ri_1

array([[19, 14, 27, 20, 10, 36, 35, 26, 29, 20],
       [32, 26, 36, 25, 34, 18, 12, 18, 32, 38],
       [36, 16, 28, 29, 10, 10, 11, 15, 35, 17],
       [34, 32, 13, 25, 35, 16, 21, 13, 24, 22],
       [31, 30, 38, 23, 19, 30, 39, 24, 29, 33],
       [23, 24, 38, 19, 30, 13, 39, 38, 21, 38],
       [12, 12, 19, 25, 16, 24, 21, 37, 33, 11],
       [27, 22, 12, 31, 14, 19, 20, 19, 18, 27],
       [22, 23, 16, 37, 33, 26, 26, 36, 13, 23],
       [34, 14, 32, 31, 14, 23, 30, 11, 21, 25]], dtype=int32)

In [33]:
ri_1.shape

(10, 10)

In [34]:
print(ri_1)

[[19 14 27 20 10 36 35 26 29 20]
 [32 26 36 25 34 18 12 18 32 38]
 [36 16 28 29 10 10 11 15 35 17]
 [34 32 13 25 35 16 21 13 24 22]
 [31 30 38 23 19 30 39 24 29 33]
 [23 24 38 19 30 13 39 38 21 38]
 [12 12 19 25 16 24 21 37 33 11]
 [27 22 12 31 14 19 20 19 18 27]
 [22 23 16 37 33 26 26 36 13 23]
 [34 14 32 31 14 23 30 11 21 25]]


In [35]:
ri_1[3:8]

array([[34, 32, 13, 25, 35, 16, 21, 13, 24, 22],
       [31, 30, 38, 23, 19, 30, 39, 24, 29, 33],
       [23, 24, 38, 19, 30, 13, 39, 38, 21, 38],
       [12, 12, 19, 25, 16, 24, 21, 37, 33, 11],
       [27, 22, 12, 31, 14, 19, 20, 19, 18, 27]], dtype=int32)

In [36]:
ri_1[3,8]

np.int32(24)

In [37]:
ri_1

array([[19, 14, 27, 20, 10, 36, 35, 26, 29, 20],
       [32, 26, 36, 25, 34, 18, 12, 18, 32, 38],
       [36, 16, 28, 29, 10, 10, 11, 15, 35, 17],
       [34, 32, 13, 25, 35, 16, 21, 13, 24, 22],
       [31, 30, 38, 23, 19, 30, 39, 24, 29, 33],
       [23, 24, 38, 19, 30, 13, 39, 38, 21, 38],
       [12, 12, 19, 25, 16, 24, 21, 37, 33, 11],
       [27, 22, 12, 31, 14, 19, 20, 19, 18, 27],
       [22, 23, 16, 37, 33, 26, 26, 36, 13, 23],
       [34, 14, 32, 31, 14, 23, 30, 11, 21, 25]], dtype=int32)

In [38]:
ri_1[9,9]

np.int32(25)

In [39]:
ri_1[0,9]

np.int32(20)

In [40]:
ri_1[-5]

array([23, 24, 38, 19, 30, 13, 39, 38, 21, 38], dtype=int32)

In [42]:
ri_1[-5,-4]

np.int32(39)

In [43]:
ri_1[::3]

array([[19, 14, 27, 20, 10, 36, 35, 26, 29, 20],
       [34, 32, 13, 25, 35, 16, 21, 13, 24, 22],
       [12, 12, 19, 25, 16, 24, 21, 37, 33, 11],
       [34, 14, 32, 31, 14, 23, 30, 11, 21, 25]], dtype=int32)

In [44]:
ri_1[::-1]

array([[34, 14, 32, 31, 14, 23, 30, 11, 21, 25],
       [22, 23, 16, 37, 33, 26, 26, 36, 13, 23],
       [27, 22, 12, 31, 14, 19, 20, 19, 18, 27],
       [12, 12, 19, 25, 16, 24, 21, 37, 33, 11],
       [23, 24, 38, 19, 30, 13, 39, 38, 21, 38],
       [31, 30, 38, 23, 19, 30, 39, 24, 29, 33],
       [34, 32, 13, 25, 35, 16, 21, 13, 24, 22],
       [36, 16, 28, 29, 10, 10, 11, 15, 35, 17],
       [32, 26, 36, 25, 34, 18, 12, 18, 32, 38],
       [19, 14, 27, 20, 10, 36, 35, 26, 29, 20]], dtype=int32)

In [45]:
ri_1[:]

array([[19, 14, 27, 20, 10, 36, 35, 26, 29, 20],
       [32, 26, 36, 25, 34, 18, 12, 18, 32, 38],
       [36, 16, 28, 29, 10, 10, 11, 15, 35, 17],
       [34, 32, 13, 25, 35, 16, 21, 13, 24, 22],
       [31, 30, 38, 23, 19, 30, 39, 24, 29, 33],
       [23, 24, 38, 19, 30, 13, 39, 38, 21, 38],
       [12, 12, 19, 25, 16, 24, 21, 37, 33, 11],
       [27, 22, 12, 31, 14, 19, 20, 19, 18, 27],
       [22, 23, 16, 37, 33, 26, 26, 36, 13, 23],
       [34, 14, 32, 31, 14, 23, 30, 11, 21, 25]], dtype=int32)

In [47]:
ri_1[::-5]

array([[34, 14, 32, 31, 14, 23, 30, 11, 21, 25],
       [31, 30, 38, 23, 19, 30, 39, 24, 29, 33]], dtype=int32)

In [48]:
ri_1

array([[19, 14, 27, 20, 10, 36, 35, 26, 29, 20],
       [32, 26, 36, 25, 34, 18, 12, 18, 32, 38],
       [36, 16, 28, 29, 10, 10, 11, 15, 35, 17],
       [34, 32, 13, 25, 35, 16, 21, 13, 24, 22],
       [31, 30, 38, 23, 19, 30, 39, 24, 29, 33],
       [23, 24, 38, 19, 30, 13, 39, 38, 21, 38],
       [12, 12, 19, 25, 16, 24, 21, 37, 33, 11],
       [27, 22, 12, 31, 14, 19, 20, 19, 18, 27],
       [22, 23, 16, 37, 33, 26, 26, 36, 13, 23],
       [34, 14, 32, 31, 14, 23, 30, 11, 21, 25]], dtype=int32)

In [50]:
print(ri_1[2])          # Specific rows will print
print(ri_1[:,2])        # specific Column will print

[36 16 28 29 10 10 11 15 35 17]
[27 36 28 13 38 38 19 12 16 32]


In [53]:
ri_1[:,8]          # print column from forward

array([29, 32, 35, 24, 29, 21, 33, 18, 13, 21], dtype=int32)

In [54]:
ri_1[:,-8]            # print column from backward

array([27, 36, 28, 13, 38, 38, 19, 12, 16, 32], dtype=int32)

In [55]:
ri_1

array([[19, 14, 27, 20, 10, 36, 35, 26, 29, 20],
       [32, 26, 36, 25, 34, 18, 12, 18, 32, 38],
       [36, 16, 28, 29, 10, 10, 11, 15, 35, 17],
       [34, 32, 13, 25, 35, 16, 21, 13, 24, 22],
       [31, 30, 38, 23, 19, 30, 39, 24, 29, 33],
       [23, 24, 38, 19, 30, 13, 39, 38, 21, 38],
       [12, 12, 19, 25, 16, 24, 21, 37, 33, 11],
       [27, 22, 12, 31, 14, 19, 20, 19, 18, 27],
       [22, 23, 16, 37, 33, 26, 26, 36, 13, 23],
       [34, 14, 32, 31, 14, 23, 30, 11, 21, 25]], dtype=int32)

In [56]:
ri_1[2:6, 5:8]

array([[10, 11, 15],
       [16, 21, 13],
       [30, 39, 24],
       [13, 39, 38]], dtype=int32)

In [57]:
ri_1[0:3 , 0:3]

array([[19, 14, 27],
       [32, 26, 36],
       [36, 16, 28]], dtype=int32)

In [58]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [59]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [60]:
np.arange(1,13).reshape(5,4)

ValueError: cannot reshape array of size 12 into shape (5,4)

In [61]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [62]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [63]:
np.arange(1,13).reshape(2,4)

ValueError: cannot reshape array of size 12 into shape (2,4)

In [64]:
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [65]:
np.arange(1,13).reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [66]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

# Numpy Masking or Filter

In [67]:
mat= np.arange(0,100).reshape(10,10)

In [68]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [69]:
id(mat)

2868477730064

In [70]:
type(mat)

numpy.ndarray

In [71]:
mat< 50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [72]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [73]:
mat[mat< 25]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [74]:
mat[mat == 50]

array([50])

In [75]:
mat[mat > 50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])