In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.5'

In [3]:
my_list=[0,1,2,3,4,5]

In [4]:
my_list

[0, 1, 2, 3, 4, 5]

In [5]:
type(my_list)

list

In [6]:
arr = np.array(my_list)

In [7]:
arr

array([0, 1, 2, 3, 4, 5])

In [8]:
type(arr)

numpy.ndarray

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [11]:
np.arange(10,20,3)

array([10, 13, 16, 19])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [14]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [15]:
np.zeros((2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [16]:
np.zeros((2,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [17]:
np.zeros((5,10), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [18]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
np.ones(10, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [20]:
np.ones((3,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [21]:
np.random.rand(4)

array([0.20546738, 0.14959925, 0.21138862, 0.43376501])

In [22]:
np.random.rand(4)

array([0.62331503, 0.12240242, 0.23092201, 0.00796598])

In [23]:
np.random.rand(4)

array([0.55479253, 0.5671935 , 0.48316761, 0.41703987])

In [24]:
np.random.rand(4)

array([0.41783933, 0.22616   , 0.87029247, 0.90394843])

In [25]:
np.random.rand((4,4))

TypeError: 'tuple' object cannot be interpreted as an integer

In [26]:
np.random.rand(4,4)

array([[0.80162344, 0.84804163, 0.7712035 , 0.96901472],
       [0.42760434, 0.70311802, 0.14587559, 0.31693445],
       [0.46009671, 0.41342472, 0.46365385, 0.76560567],
       [0.81838943, 0.55720225, 0.0997881 , 0.01622166]])

In [27]:
np.random.rand(2,2)

array([[0.57045315, 0.42689974],
       [0.08013396, 0.97845116]])

In [28]:
np.random.rand(4, dtype=int)

TypeError: rand() got an unexpected keyword argument 'dtype'

In [29]:
np.random.randint(4)

1

In [30]:
np.random.randint(4)

3

In [31]:
np.random.randint(4)

2

In [32]:
np.random.randint(4)

2

In [39]:
np.random.randint(4)

3

In [41]:
np.random.randint(0,3)

2

In [46]:
np.random.randint(10,15)

11

In [47]:
np.random.randint(10,15)

14

In [52]:
np.random.randint(1000,9999)

7607

In [53]:
np.zeros((4,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])